import React, { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

export const translations = {
  english: {
    // Common
    search: 'Search',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    close: 'Close',
    submit: 'Submit',
    refresh: 'Refresh',
    welcome: 'Welcome',
    processing: 'Processing...',
    loading: 'Loading...',
    noData: 'No data available',
    error: 'Error',
    success: 'Success',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    
    // Header
    aiVoiceBilling: 'AI Voice Billing',
    signUpFree: 'Sign Up Free',
    
    // Guest Banner
    exploringDemoMode: "You're exploring Demo Mode",
    withSampleData: 'with sample data',
    signUpToSave: '— Sign up free to save your real inventory, bills, and customer data!',
    
    // Authentication
    login: 'Sign In',
    register: 'Sign Up',
    signIn: 'Sign in',
    signUp: 'Sign up',
    username: 'User Name',
    password: 'Password',
    email: 'Email',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    chooseLoginMethod: 'Choose your preferred login method',
    createAccountMessage: 'Create an account to get started',
    loginWelcomeMessage: 'Experience the future of billing with AI-powered voice recognition and smart inventory management.',
    registerWelcomeMessage: 'Join us to unlock powerful features for your business with AI-powered voice billing and inventory management.',
    
    // Sidebar
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    voiceBilling: 'Voice Billing',
    udharKhata: 'Udhar Khata',
    billHistory: 'Bill History',
    reports: 'Reports',
    settings: 'Settings',
    logout: 'Logout',
    confirmLogout: 'Are you sure you want to logout?',
    
    // Dashboard
    todaySales: "Today's Sales",
    totalItems: 'Total Items',
    lowStock: 'Low Stock',
    udharAmount: 'Udhar Amount',
    topSellingItems: 'Top Selling Items',
    lowStockAlerts: 'Low Stock Alerts',
    itemName: 'Item Name',
    stock: 'Stock',
    status: 'Status',
    action: 'Action',
    restock: 'Restock',
    quickActions: 'Quick Actions',
    inStock: 'in stock',
    
    // Inventory
    inventoryManagement: 'Inventory Management',
    addNewItem: 'Add New Item',
    price: 'Price',
    unit: 'Unit',
    quantity: 'Quantity',
    outOfStock: 'Out of Stock',
    critical: 'Critical',
    low: 'Low',
    good: 'Good',
    searchItems: 'Search items...',
    allStatus: 'All Status',
    actions: 'Actions',
    noItemsFound: 'No items found',
    
    // Voice Billing
    manualBilling: 'Manual Billing',
    voiceInputBilling: 'Voice Input Billing',
    cart: 'Cart',
    total: 'Total',
    generateBill: 'Generate Bill',
    clearCart: 'Clear Cart',
    addToCart: 'Add to Cart',
    availableItems: 'Available Items',
    currentBill: 'Current Bill',
    clickMicrophoneToSpeak: 'Click microphone to speak',
    available: 'Available',
    cash: 'Cash',
    credit: 'Credit',
    selectCustomer: 'Select Customer',
    addToUdhar: 'Add to Udhar',
    payNow: 'Pay Now',
    paymentMethod: 'Payment Method',
    cashPayment: 'Cash Payment',
    udharPayment: 'Udhar Payment',
    searchCustomer: 'Search for customer...',
    selectPaymentType: 'Select Payment Type',
    
    // Udhar Khata
    udharManagement: 'Udhar Management',
    addCustomer: 'Add Customer',
    customerName: 'Customer Name',
    totalUdhar: 'Total Udhar',
    viewDetails: 'View Details',
    totalUnpaid: 'Total Unpaid',
    totalPaid: 'Total Paid',
    totalCustomers: 'Total Customers',
    filter: 'Filter',
    all: 'All',
    unpaid: 'Unpaid',
    paid: 'Paid',
    addNewEntry: 'Add New Entry',
    pending: 'PENDING',
    completed: 'COMPLETED',
    payUdhar: 'Pay Udhar',
    completedPayments: 'Completed payments',
    addNewUdharEntry: 'Add New Udhar Entry',
    addEntry: 'Add Entry',
    addUdharAmount: 'Add Udhar Amount',
    amountToAdd: 'Amount to Add',
    enterAmountToAdd: 'Enter amount to add',
    newTotalWillBe: 'New total will be',
    cannotDeleteCustomer: 'Cannot Delete Customer',
    stillHasPending: 'still has pending udhar of',
    collectRemaining: 'Please collect the remaining udhar amount before deleting this customer.',
    payUdharNow: 'Pay Udhar Now',
    currentAmount: 'Current Amount',
    paymentAmount: 'Payment Amount',
    enterAmountToPay: 'Enter amount to pay',
    remainingAmount: 'Remaining Amount',
    noCustomersFound: 'No customers found',
    processPayment: 'Process Payment',
    maximum: 'Maximum',
    viewItems: 'View Items',
    udharItems: 'Udhar Items',
    
    // Reports
    reportsAnalytics: 'Reports & Analytics',
    dateRange: 'Date Range',
    category: 'Category',
    allCategories: 'All Categories',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    thisYear: 'This Year',
    totalRevenue: 'Total Revenue',
    totalProfit: 'Total Profit',
    totalTransactions: 'Total Transactions',
    avgTransaction: 'Avg. Transaction',
    dailySalesTrend: 'Daily Sales Trend',
    itemFrequency: 'Item Frequency',
    salesSummary: 'Sales Summary',
    product: 'Product',
    totalSale: 'Total Sale',
    generating: 'Generating...',
    downloadReport: 'Download Report',
    noDataAvailable: 'No data available',
    noSalesData: 'No sales data for the selected period',
    profit: 'Profit',
    
    // Settings
    settingsTitle: 'Settings',
    appearance: 'Appearance',
    themeMode: 'Theme Mode',
    light: 'Light',
    dark: 'Dark',
    language: 'Language',
    displayLanguage: 'Display Language',
    userManagement: 'User Management',
    about: 'About',
    version: 'Version',
    builtWith: 'Built with',
    purpose: 'Purpose',
    
    // Bill History
    billHistoryTitle: 'Bill History',
    viewAndManageBills: 'View and manage all generated bills',
    todayTotal: "Today's Total",
    cashSales: 'Cash Sales',
    udharSales: 'Udhar Sales',
    searchBillOrCustomer: 'Search bill number or customer...',
    paymentType: 'Payment Type',
    allPayments: 'All Payments',
    allBills: 'All Bills',
    allBillsList: 'All Bills',
    byCustomer: 'By Customer',
    viewAllBills: 'View All Bills',
    allBillsOf: 'All Bills',
    cashOnly: 'Cash Only',
    creditOnly: 'Credit Only',
    startDate: 'Start Date',
    endDate: 'End Date',
    billNumber: 'Bill Number',
    customer: 'Customer',
    date: 'Date',
    dateTime: 'Date & Time',
    type: 'Type',
    amount: 'Amount',
    items: 'Items',
    walkInCustomer: 'Walk-in Customer',
    viewReceipt: 'View Receipt',
    noBillsFound: 'No bills found',
    deleteBillConfirm: 'Are you sure you want to delete this bill?',
    billDeleted: 'Bill deleted successfully!',
    failedToDeleteBill: 'Failed to delete bill',
    
    // Voice Billing - Additional
    noItemsAdded: 'No items added yet. Use voice command to add items.',
    qty: 'Qty',
    grandTotal: 'Grand Total',
    item: 'Item',
    completeBill: 'Complete Bill',
    totalAmount: 'Total Amount',
    howToProceed: 'How would you like to proceed?',
    creditSale: 'Credit Sale',
    viewBill: 'View Bill',
    deleteBill: 'Delete Bill',
    searchForCustomer: 'Search for customer to add',
    toTheirUdhar: 'to their Udhar',
    searchCustomerName: 'Search customer name...',
    currentUdhar: 'Current Udhar',
    newTotal: 'New Total',
    noCustomerFound: 'No customer found with name',
    addCustomerFirst: 'Please add this customer in Udhar Khata first',
    addedToUdhar: 'added to',
    udharAccount: "'s Udhar account.",
    inventoryUpdated: 'Inventory updated!',
    transactionId: 'Transaction ID:',
    paidBy: 'Paid By:',
    purchase: 'Purchase',
    subTotal: 'Sub Total',
    salesTax: 'Sales Tax',
    thankYou: 'THANK YOU FOR',
    yourPurchase: 'YOUR PURCHASE',
    print: 'Print',
    visitAgain: 'Visit us again!',
    transactionCompleted: 'Transaction completed successfully',
    billGeneratedSuccess: 'Bill generated successfully! Inventory has been updated.',
    editItem: 'Edit Item',
    egSugar: 'e.g., Sugar',
    unitPrice: 'Unit Price',
    addItem: 'Add Item',
    updateItem: 'Update Item',
    confirmDelete: 'Are you sure you want to delete this item?',
    failedToDelete: 'Failed to delete item',
    cannotDeleteItem: 'Cannot delete this item because it has related records',
    
    // Udhar Khata - Additional
    addUdhar: 'Add Udhar',
    
    // Settings - Additional
    voiceAuthentication: 'Voice Authentication',
    registerVoice: 'Register Voice',
    notRegistered: 'Not registered',
    registerVoiceDesc: 'Register your voice to enable voice-based login. This is an additional security feature.',
    owner: 'Owner',
    registered: 'Registered',
    checking: 'Checking...',
    reRegisterVoice: 'Re-register Voice',
    voiceRegisteredDesc: 'Your voice is registered. You can now login using voice authentication.',
    readThisParagraph: 'Read this paragraph clearly:',
    processingVoice: 'Processing your voice...',
    noUserLoggedIn: 'No user logged in',
    active: 'Active',
    
    // Login/Register
    fullName: 'Full Name',
    confirmPassword: 'Confirm Password',
    
    // Dashboard - Additional
    overview: 'Over View',
    totalProducts: 'Total Products',
    orders: 'Orders',
    totalStock: 'Total Stock',
    allGood: 'All Good',
    loadingDashboardData: 'Loading dashboard data...',
    noSalesYet: 'No sales yet',
    numberOfUsers: 'No of users',
    inventoryValues: 'Inventory Values',
    soldUnitsLabel: 'Sold units',
    totalUnitsLabel: 'Total units',
    topStoresBySales: 'Top Selling Items',
    monthlyRevenueLabel: 'Monthly Revenue',
    lastSixMonths: 'Last 6 months',
    noSalesDataYet: 'No sales data yet',
    
    // Sales - Additional
    salesManagement: 'Sales Management & Analytics',
    salesDescription: 'Advanced sales analytics, returns processing, and performance tracking',
    last7Days: 'Last 7 Days',
    last30Days: 'Last 30 Days',
    lastYear: 'Last Year',
    salesAnalytics: 'Sales Analytics',
    returnsAndRefunds: 'Returns & Refunds',
    salesTargetProgress: 'Sales Target Progress',
    targetLabel: 'Target',
    itemsSold: 'Items Sold',
    returnsProcessed: 'Returns Processed',
    refunded: 'refunded',
    hourlySalesBreakdown: 'Hourly Sales Breakdown',
    salesByCategory: 'Sales by Category',
    salesByPaymentMethod: 'Sales by Payment Method',
    bestSellingItems: 'Best Selling Items',
    quantitySold: 'Quantity Sold',
    revenue: 'Revenue',
    profitMarginByItem: 'Profit Margin by Item',
    totalReturns: 'Total Returns',
    totalRefunded: 'Total Refunded',
    returnRate: 'Return Rate',
    selectBillForReturn: 'Select Bill for Return',
    processReturnTitle: 'Process Return',
    processReturnBtn: 'Process Return',
    processReturnAndRefund: 'Process Return & Refund',
    returnHistory: 'Return History',
    noReturnsYet: 'No returns processed yet',
    returnType: 'Return Type',
    fullReturn: 'Full Return',
    returnAllItems: 'Return all items',
    partialReturn: 'Partial Return',
    selectSpecificItems: 'Select specific items',
    itemsToReturn: 'Items to Return',
    returnQty: 'Return Qty',
    returnReason: 'Return Reason *',
    selectAReason: 'Select a reason...',
    defectiveProduct: 'Defective Product',
    wrongItemDelivered: 'Wrong Item Delivered',
    customerChangedMind: 'Customer Changed Mind',
    expiredProduct: 'Expired Product',
    qualityIssues: 'Quality Issues',
    other: 'Other',
    refundAmount: 'Refund Amount',
    profitMargin: '30% margin',
    walkIn: 'Walk-in',
    reasonLabel: 'Reason',
    
    // Forecasting
    demandForecasting: 'Demand Forecasting & Analysis',
    forecastingDescription: 'Predictive insights to optimize inventory levels and prevent stockouts',
    analysisPeriod: 'Analysis Period',
    last60Days: 'Last 60 Days',
    last90Days: 'Last 90 Days',
    criticalItems: 'Critical Items',
    needsImmediateAttention: 'Needs immediate attention',
    stockoutRisk: 'Stockout Risk',
    within14Days: 'Within 14 days',
    highDemandItems: 'High Demand Items',
    strongSalesVelocity: 'Strong sales velocity',
    reorderRequired: 'Reorder Required',
    belowReorderPoint: 'Below reorder point',
    stockLevelForecast: 'Stock Level Forecast (Next 30 Days)',
    criticalStockAlerts: 'Critical Stock Alerts',
    currentStockLabel: 'Current Stock',
    avgDailySales: 'Avg Daily Sales',
    daysUntilStockout: 'Days Until Stockout',
    reorderRecommendations: 'Reorder Recommendations',
    reorderPointLabel: 'Reorder Point',
    suggestedOrder: 'Suggested Order',
    unitsLabel: 'units',
    reorderNow: 'Reorder Now',
    allItemsWellStocked: 'All items are well-stocked!',
    highDemand: 'High Demand',
    mediumDemand: 'Medium',
    lowDemandLabel: 'Low Demand',
    noSalesLabel: 'No Sales',
    lowDemandItems: 'Low Demand / Slow Moving Items',
    considerPromotion: 'Consider promotion or clearance',
    allItemsGoodVelocity: 'All items have good sales velocity',
    stockoutRiskTimeline: 'Stockout Risk Timeline (Next 14 Days)',
    untilStockout: 'until stockout',
    dailyRate: 'Daily Rate',
    unitsPerDay: 'units/day',
    noHighDemandItems: 'No high demand items in this period',
    soldLabel: 'Sold',
    dailyAvg: 'Daily Avg',
    forecasting: 'Forecasting',
    
    // VoiceBilling - Additional
    billingSystem: 'Billing System',
    transcribed: 'Transcribed',
    parsedItemLabel: 'Parsed Item',
    itemNameLabel: 'Item Name',
    quantityLabel: 'Quantity',
    unitPriceLabel: 'Unit Price',
    totalLabel: 'Total',
    addToBill: 'Add to Bill',
    loadingItems: 'Loading items...',
    tryAddingItemsFirst: 'Try adding items in Inventory page first',
    
    // Header
    welcomeUser: 'Welcome',
    
    // Sidebar - Additional
    sales: 'Sales',
    
    // Login - Additional
    brandName: 'E-Inventory',
    brandTagline: 'Online inventory management system',
    emailAddress: 'Email Address',
    keepMeLoggedIn: 'Keep me logged in',
    loggingIn: 'Logging in...',
    logIn: 'Log in',
    loginWithVoice: 'Login With Voice',
    registerHere: 'Register here',
    voiceLoginTitle: 'Voice Login',
    verifying: 'Verifying...',
    recordingClickToStop: 'Recording... Click to stop',
    tapToSpeak: 'Tap to speak',
    backToEmailLogin: 'Back to Email Login',
    
    // Register - Additional
    createAccount: 'Create Account',
    creatingAccount: 'Creating account...',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordMinLength: 'Password must be at least 6 characters',
    
    // Receipt - Additional
    newBill: 'New Bill',
    printReceipt: 'Print Receipt',
    
    // Bill History - Additional
    todaysBills: "Today's Bills",
    billDetails: 'Bill Details',
    
    // Settings - Additional voice
    recordingDuration: 'Recording... (5 seconds)',
    voiceRecorded: 'Voice recorded!',
    tapToRecord: 'Tap to record',
    readParagraphWhileRecording: 'Read the paragraph above while recording',
    registerThisVoice: 'Register This Voice',
    reRecord: 'Re-record',

    // Header and global search - Additional
    unnamedItem: 'Unnamed Item',
    featureLabel: 'Feature',
    userFallback: 'User',
    searching: 'Searching...',
    switchToLightMode: 'Switch to Light Mode',
    switchToDarkMode: 'Switch to Dark Mode',
    stockAlerts: 'Stock Alerts',
    alertSingle: 'alert',
    alertsPlural: 'alerts',
    criticalStockOnlyLeft: 'Critical stock - only',
    lowStockLeft: 'Low stock -',
    reorderAt: 'reorder at',
    confirmLogoutTitle: 'Confirm Logout',
    confirmLogoutGuestModeMessage: 'Are you sure you want to log out? You will be switched to guest mode.',
    yesLogout: 'Yes, Logout',

    // Settings account edit - Additional
    editAccountInfo: 'Edit Account Info',
    pleaseLoginToEditAccount: 'Please login first to edit account details.',
    newPassword: 'New Password',
    leaveEmptyToKeepCurrent: 'Leave empty to keep current',
    reEnterNewPassword: 'Re-enter new password',
    saving: 'Saving...',
    saveChanges: 'Save Changes',
    usernameRequired: 'Username is required',
    emailRequired: 'Email is required',
    profileUpdatedSuccessfully: 'Profile updated successfully',
    failedToUpdateProfile: 'Failed to update profile',
    pleaseRecordVoiceFirst: 'Please record your voice first',
    voiceRegisteredSuccessMessage: 'Voice registered successfully! You can now login with your voice.',
    voiceRegistrationFailed: 'Voice registration failed',
    voiceRegistrationParagraph: 'Please read: "The quick brown fox jumps over the lazy dog. My voice is my password verify."',
    
    // Reports - Additional
    loadingReports: 'Loading reports...',
    salesCount: 'Sales count',
    perSale: 'Per sale',
    profitMarginPct: '20% margin',
    
    // Inventory - Additional
    retryConnection: 'Retry Connection',
    loadingItemsMsg: 'Loading items...',
    
    // Sales table headers
    searchByBillOrCustomer: 'Search by bill number or customer name...',
    qtyLabel: 'Qty',
    priceLabel: 'Price',
    billLabel: 'Bill',
    daysLabel: 'days',
    currentLabel: 'Current',
    predictedDemand30d: 'Predicted Demand (30d)',
    
    // Misc
    egAhmedAli: 'e.g., Ahmed Ali',
    loadingData: 'Loading data...',
    failedToLoadData: 'Failed to load data. Please try again.',
    unableToLoadPlsRefresh: 'Unable to load data. Please refresh the page.',
    deleteLabel: 'Delete',

    // Alert dialog
    ok: 'OK',
    alertError: 'Error',
    alertSuccess: 'Success',
    alertWarning: 'Warning',
    alertInfo: 'Info',

    // VoiceBilling alerts
    failedToLoadItems: 'Failed to load items',
    pleaseTryAgain: 'Please try again',
    insufficientStock: 'Insufficient Stock',
    insufficientStockMsg: 'Available: {stock} {unit}',
    noItemsInBill: 'No items in bill!',
    itemNotFoundInInventory: '{name} not found in inventory!',
    insufficientStockForItem: 'Insufficient stock for {name}! Available: {stock} {unit}',
    failedToAddToUdhar: 'Failed to add to udhar',
    failedToUpdateInventory: 'Failed to update inventory',
    pleaseEnterValidQty: 'Please enter a valid quantity',
    onlyXAvailable: 'Only {stock} {unit} available!',

    // Inventory alerts
    failedToAddItem: 'Failed to add item',
    failedToUpdateItem: 'Failed to update item',
    confirmDeleteItem: 'Are you sure you want to delete this item?',

    // UdharKhata alerts
    pleaseEnterCustomerName: 'Please enter customer name',
    failedToAddEntry: 'Failed to add entry',
    pleaseEnterValidAmountGt0: 'Please enter a valid amount greater than 0',
    failedToAddUdhar: 'Failed to add udhar',
    confirmDeleteCustomer: 'Are you sure you want to delete {name}? This will remove all their records.',
    customerDeletedSuccess: 'Customer deleted successfully!',
    failedToDeleteCustomer: 'Failed to delete',
    pleaseEnterValidAmount: 'Please enter a valid amount',
    paymentExceedsUdhar: 'Payment amount cannot exceed the current udhar amount',
    failedToProcessPayment: 'Failed to process payment',

    // BillHistory alerts
    failedToLoadBills: 'Failed to load bills',

    // Reports alerts
    noReportData: 'No report data available to download.',
    failedToDownloadReport: 'Failed to download report. Please try again.',

    // Sales alerts
    pleaseSelectItemsToReturn: 'Please select items to return',
    pleaseProvideReturnReason: 'Please provide a return reason',
    returnProcessedSuccess: 'Return processed successfully!',
    refundAmountLabel: 'Refund Amount: ₨{amount}',
    failedToProcessReturn: 'Failed to process return. Please try again.',
  },
  urdu: {
    // Common
    search: 'تلاش کریں',
    save: 'محفوظ کریں',
    cancel: 'منسوخ کریں',
    delete: 'حذف کریں',
    edit: 'تدوین کریں',
    add: 'شامل کریں',
    close: 'بند کریں',
    submit: 'جمع کرائیں',
    refresh: 'تازہ کریں',
    welcome: 'خوش آمدید',
    processing: 'کارروائی جاری ہے...',
    loading: 'لوڈ ہو رہا ہے...',
    noData: 'کوئی ڈیٹا دستیاب نہیں',
    error: 'خرابی',
    success: 'کامیابی',
    confirm: 'تصدیق کریں',
    yes: 'ہاں',
    no: 'نہیں',
    
    // Header
    aiVoiceBilling: 'اے آئی وائس بلنگ',
    signUpFree: 'مفت سائن اپ',
    
    // Guest Banner
    exploringDemoMode: 'آپ ڈیمو موڈ دیکھ رہے ہیں',
    withSampleData: 'نمونہ ڈیٹا کے ساتھ',
    signUpToSave: '— اپنی حقیقی انوینٹری، بل اور گاہک کا ڈیٹا محفوظ کرنے کے لیے مفت سائن اپ کریں!',
    
    // Authentication
    login: 'سائن ان',
    register: 'رجسٹر کریں',
    signIn: 'سائن ان',
    signUp: 'رجسٹر کریں',
    username: 'صارف کا نام',
    password: 'پاس ورڈ',
    email: 'ای میل',
    dontHaveAccount: 'اکاؤنٹ نہیں ہے؟',
    alreadyHaveAccount: 'پہلے سے اکاؤنٹ ہے؟',
    chooseLoginMethod: 'اپنا پسندیدہ لاگ ان طریقہ منتخب کریں',
    createAccountMessage: 'شروع کرنے کے لیے ایک اکاؤنٹ بنائیں',
    loginWelcomeMessage: 'AI سے چلنے والی وائس ریکگنیشن اور سمارٹ انوینٹری مینجمنٹ کے ساتھ بلنگ کے مستقبل کا تجربہ کریں۔',
    registerWelcomeMessage: 'AI سے چلنے والی وائس بلنگ اور انوینٹری مینجمنٹ کے ساتھ اپنے کاروبار کے لیے طاقتور خصوصیات کو غیر مقفل کرنے کے لیے ہم سے جڑیں۔',
    
    // Sidebar
    dashboard: 'ڈیش بورڈ',
    inventory: 'انوینٹری',
    voiceBilling: 'وائس بلنگ',
    udharKhata: 'ادھار کھاتہ',
    billHistory: 'بل کی تاریخ',
    reports: 'رپورٹس',
    settings: 'ترتیبات',
    logout: 'لاگ آؤٹ',
    confirmLogout: 'کیا آپ واقعی لاگ آؤٹ کرنا چاہتے ہیں؟',
    
    // Dashboard
    todaySales: 'آج کی فروخت',
    totalItems: 'کل اشیاء',
    lowStock: 'کم اسٹاک',
    udharAmount: 'ادھار رقم',
    topSellingItems: 'زیادہ فروخت ہونے والی اشیاء',
    lowStockAlerts: 'کم اسٹاک الرٹس',
    itemName: 'آئٹم کا نام',
    stock: 'اسٹاک',
    status: 'حالت',
    action: 'ایکشن',
    restock: 'دوبارہ اسٹاک',
    quickActions: 'فوری کارروائیاں',
    inStock: 'اسٹاک میں',
    todayTotal: 'آج کا کل',
    
    // Inventory
    inventoryManagement: 'انوینٹری مینجمنٹ',
    addNewItem: 'نیا آئٹم شامل کریں',
    price: 'قیمت',
    unit: 'یونٹ',
    quantity: 'مقدار',
    outOfStock: 'اسٹاک ختم',
    critical: 'نازک',
    low: 'کم',
    good: 'اچھا',
    searchItems: 'اشیاء تلاش کریں...',
    allStatus: 'تمام حالت',
    actions: 'اقدامات',
    noItemsFound: 'کوئی آئٹم نہیں ملا',
    
    // Voice Billing
    manualBilling: 'دستی بلنگ',
    voiceInputBilling: 'آواز سے بلنگ',
    cart: 'کارٹ',
    total: 'کل',
    generateBill: 'بل بنائیں',
    clearCart: 'کارٹ صاف کریں',
    addToCart: 'کارٹ میں شامل کریں',
    availableItems: 'دستیاب اشیاء',
    currentBill: 'موجودہ بل',
    clickMicrophoneToSpeak: 'بولنے کے لیے مائیکروفون پر کلک کریں',
    available: 'دستیاب',
    cash: 'نقد',
    credit: 'ادھار',
    selectCustomer: 'گاہک منتخب کریں',
    addToUdhar: 'ادھار میں شامل کریں',
    payNow: 'ابھی ادا کریں',
    paymentMethod: 'ادائیگی کا طریقہ',
    cashPayment: 'نقد ادائیگی',
    udharPayment: 'ادھار ادائیگی',
    searchCustomer: 'گاہک تلاش کریں...',
    selectPaymentType: 'ادائیگی کی قسم منتخب کریں',
    
    // Udhar Khata
    udharManagement: 'ادھار مینجمنٹ',
    addCustomer: 'نیا گاہک شامل کریں',
    customerName: 'گاہک کا نام',
    totalUdhar: 'کل ادھار',
    viewDetails: 'تفصیلات دیکھیں',
    totalUnpaid: 'کل ادائیگی نہیں',
    totalPaid: 'کل ادا شدہ',
    totalCustomers: 'کل گاہک',
    filter: 'فلٹر',
    all: 'تمام',
    unpaid: 'ادائیگی نہیں',
    paid: 'ادا شدہ',
    addNewEntry: 'نیا اندراج شامل کریں',
    pending: 'زیر التواء',
    completed: 'مکمل',
    payUdhar: 'ادھار ادا کریں',
    completedPayments: 'مکمل ادائیگیاں',
    addNewUdharEntry: 'نیا ادھار اندراج شامل کریں',
    addEntry: 'اندراج شامل کریں',
    addUdharAmount: 'ادھار رقم شامل کریں',
    amountToAdd: 'شامل کرنے کی رقم',
    enterAmountToAdd: 'شامل کرنے کی رقم درج کریں',
    newTotalWillBe: 'نیا کل ہوگا',
    cannotDeleteCustomer: 'گاہک حذف نہیں کر سکتے',
    stillHasPending: 'ابھی بھی باقی ہے ادھار',
    collectRemaining: 'براہ کرم اس گاہک کو حذف کرنے سے پہلے باقی ادھار رقم وصول کریں۔',
    payUdharNow: 'ابھی ادھار ادا کریں',
    currentAmount: 'موجودہ رقم',
    paymentAmount: 'ادائیگی کی رقم',
    enterAmountToPay: 'ادا کرنے کی رقم درج کریں',
    remainingAmount: 'باقی رقم',
    noCustomersFound: 'کوئی گاہک نہیں ملا',
    processPayment: 'ادائیگی کی کارروائی',
    maximum: 'زیادہ سے زیادہ',
    viewItems: 'اشیاء دیکھیں',
    udharItems: 'ادھار اشیاء',
    
    // Reports
    reportsAnalytics: 'رپورٹس اور تجزیہ',
    dateRange: 'تاریخ کی حد',
    category: 'زمرہ',
    allCategories: 'تمام زمرے',
    today: 'آج',
    thisWeek: 'اس ہفتے',
    thisMonth: 'اس ماہ',
    thisYear: 'اس سال',
    totalRevenue: 'کل آمدنی',
    totalProfit: 'کل منافع',
    totalTransactions: 'کل لین دین',
    avgTransaction: 'اوسط لین دین',
    dailySalesTrend: 'روزانہ فروخت کا رجحان',
    itemFrequency: 'آئٹم کی تعدد',
    salesSummary: 'فروخت کا خلاصہ',
    product: 'پروڈکٹ',
    totalSale: 'کل فروخت',
    generating: 'تیار کیا جا رہا ہے...',
    downloadReport: 'رپورٹ ڈاؤن لوڈ کریں',
    noDataAvailable: 'کوئی ڈیٹا دستیاب نہیں',
    noSalesData: 'منتخب مدت کے لیے کوئی فروخت کا ڈیٹا نہیں',
    profit: 'منافع',
    
    // Settings
    settingsTitle: 'ترتیبات',
    appearance: 'ظاہری شکل',
    themeMode: 'تھیم موڈ',
    light: 'روشن',
    dark: 'تاریک',
    language: 'زبان',
    displayLanguage: 'ڈسپلے زبان',
    userManagement: 'صارف کا انتظام',
    about: 'کے بارے میں',
    version: 'ورژن',
    builtWith: 'بنایا گیا',
    purpose: 'مقصد',
    
    // Bill History
    billHistoryTitle: 'بل کی تاریخ',
    viewAndManageBills: 'تمام بنائے گئے بل دیکھیں اور ان کا انتظام کریں',
    cashSales: 'نقد فروخت',
    udharSales: 'ادھار فروخت',
    searchBillOrCustomer: 'بل نمبر یا گاہک تلاش کریں...',
    paymentType: 'ادائیگی کی قسم',
    allPayments: 'تمام ادائیگیاں',
    allBills: 'تمام بل',
    allBillsList: 'تمام بل',
    byCustomer: 'گاہک کے مطابق',
    viewAllBills: 'تمام بل دیکھیں',
    allBillsOf: 'کے تمام بل',
    cashOnly: 'صرف نقد',
    creditOnly: 'صرف ادھار',
    startDate: 'شروع کی تاریخ',
    endDate: 'اختتام کی تاریخ',
    billNumber: 'بل نمبر',
    customer: 'گاہک',
    date: 'تاریخ',
    dateTime: 'تاریخ اور وقت',
    type: 'قسم',
    amount: 'رقم',
    items: 'اشیاء',
    walkInCustomer: 'واک ان گاہک',
    viewReceipt: 'رسید دیکھیں',
    noBillsFound: 'کوئی بل نہیں ملا',
    deleteBillConfirm: 'کیا آپ واقعی یہ بل حذف کرنا چاہتے ہیں؟',
    billDeleted: 'بل کامیابی سے حذف ہو گیا!',
    failedToDeleteBill: 'بل حذف کرنے میں ناکامی',
    
    // Voice Billing - Additional
    noItemsAdded: 'ابھی تک کوئی آئٹم شامل نہیں کیا گیا۔ آئٹم شامل کرنے کے لیے وائس کمانڈ استعمال کریں۔',
    qty: 'مقدار',
    grandTotal: 'مجموعی کل',
    item: 'آئٹم',
    completeBill: 'بل مکمل کریں',
    totalAmount: 'کل رقم',
    howToProceed: 'آپ کیسے آگے بڑھنا چاہتے ہیں؟',
    creditSale: 'ادھار فروخت',
    viewBill: 'بل دیکھیں',
    deleteBill: 'بل حذف کریں',
    searchForCustomer: 'گاہک تلاش کریں',
    toTheirUdhar: 'ان کے ادھار میں شامل کریں',
    searchCustomerName: 'گاہک کا نام تلاش کریں...',
    currentUdhar: 'موجودہ ادھار',
    newTotal: 'نیا کل',
    noCustomerFound: 'کوئی گاہک نہیں ملا',
    addCustomerFirst: 'براہ کرم پہلے اس گاہک کو ادھار کھاتہ میں شامل کریں',
    addedToUdhar: 'میں شامل',
    udharAccount: 'کے ادھار اکاؤنٹ میں۔',
    inventoryUpdated: 'انوینٹری اپ ڈیٹ ہو گئی!',
    transactionId: 'لین دین کی شناخت:',
    paidBy: 'ادا کنندہ:',
    purchase: 'خریداری',
    subTotal: 'ذیلی کل',
    salesTax: 'سیلز ٹیکس',
    thankYou: 'آپ کا شکریہ',
    yourPurchase: 'آپ کی خریداری کے لیے',
    print: 'پرنٹ',
    visitAgain: 'دوبارہ تشریف لائیں!',
    transactionCompleted: 'لین دین کامیابی سے مکمل ہو گیا',
    billGeneratedSuccess: 'بل کامیابی سے بن گیا! انوینٹری اپ ڈیٹ ہو گئی۔',
    editItem: 'آئٹم میں ترمیم کریں',
    egSugar: 'مثال، چینی',
    unitPrice: 'یونٹ کی قیمت',
    addItem: 'آئٹم شامل کریں',
    updateItem: 'آئٹم اپ ڈیٹ کریں',
    confirmDelete: 'کیا آپ واقعی اس آئٹم کو حذف کرنا چاہتے ہیں؟',
    failedToDelete: 'آئٹم حذف کرنے میں ناکامی',
    cannotDeleteItem: 'اس آئٹم کو حذف نہیں کیا جا سکتا کیونکہ اس کے متعلقہ ریکارڈ موجود ہیں',
    
    // Udhar Khata - Additional
    addUdhar: 'ادھار شامل کریں',
    
    // Settings - Additional
    voiceAuthentication: 'وائس کی تصدیق',
    registerVoice: 'آواز رجسٹر کریں',
    notRegistered: 'رجسٹرڈ نہیں',
    registerVoiceDesc: 'وائس پر مبنی لاگ ان کو فعال کرنے کے لیے اپنی آواز رجسٹر کریں۔ یہ ایک اضافی سیکیورٹی فیچر ہے۔',
    owner: 'مالک',
    registered: 'رجسٹرڈ',
    checking: 'چیک کر رہے ہیں...',
    reRegisterVoice: 'آواز دوبارہ رجسٹر کریں',
    voiceRegisteredDesc: 'آپ کی آواز رجسٹرڈ ہے۔ اب آپ وائس کی تصدیق کا استعمال کرتے ہوئے لاگ ان کر سکتے ہیں۔',
    readThisParagraph: 'اس پیراگراف کو واضح طور پر پڑھیں:',
    processingVoice: 'آپ کی آواز پر کارروائی ہو رہی ہے...',
    noUserLoggedIn: 'کوئی صارف لاگ ان نہیں',
    active: 'فعال',
    
    // Login/Register
    fullName: 'پورا نام',
    confirmPassword: 'پاس ورڈ کی تصدیق کریں',
    
    // Dashboard - Additional
    overview: 'جائزہ',
    totalProducts: 'کل مصنوعات',
    orders: 'آرڈرز',
    totalStock: 'کل اسٹاک',
    allGood: 'سب ٹھیک',
    loadingDashboardData: 'ڈیش بورڈ ڈیٹا لوڈ ہو رہا ہے...',
    noSalesYet: 'ابھی تک کوئی فروخت نہیں',
    numberOfUsers: 'گاہکوں کی تعداد',
    inventoryValues: 'انوینٹری اقدار',
    soldUnitsLabel: 'فروخت شدہ یونٹس',
    totalUnitsLabel: 'کل یونٹس',
    topStoresBySales: 'زیادہ فروخت ہونے والی اشیاء',
    monthlyRevenueLabel: 'ماہانہ آمدنی',
    lastSixMonths: 'آخری 6 ماہ',
    noSalesDataYet: 'ابھی تک فروخت کا ڈیٹا نہیں',
    
    // Sales - Additional
    salesManagement: 'سیلز مینجمنٹ اور تجزیات',
    salesDescription: 'جدید سیلز تجزیات، واپسی کی کارروائی، اور کارکردگی کی نگرانی',
    last7Days: 'آخری 7 دن',
    last30Days: 'آخری 30 دن',
    lastYear: 'پچھلا سال',
    salesAnalytics: 'سیلز تجزیات',
    returnsAndRefunds: 'واپسی اور رقم کی واپسی',
    salesTargetProgress: 'سیلز ہدف کی پیش رفت',
    targetLabel: 'ہدف',
    itemsSold: 'فروخت شدہ اشیاء',
    returnsProcessed: 'واپسیاں مکمل',
    refunded: 'واپس کی گئی',
    hourlySalesBreakdown: 'گھنٹے وار فروخت کی تفصیل',
    salesByCategory: 'زمرے کے مطابق فروخت',
    salesByPaymentMethod: 'ادائیگی کے طریقے کے مطابق فروخت',
    bestSellingItems: 'سب سے زیادہ فروخت ہونے والی اشیاء',
    quantitySold: 'فروخت شدہ مقدار',
    revenue: 'آمدنی',
    profitMarginByItem: 'آئٹم کے مطابق منافع',
    totalReturns: 'کل واپسیاں',
    totalRefunded: 'کل واپس شدہ رقم',
    returnRate: 'واپسی کی شرح',
    selectBillForReturn: 'واپسی کے لیے بل منتخب کریں',
    processReturnTitle: 'واپسی کی کارروائی',
    processReturnBtn: 'واپسی کی کارروائی',
    processReturnAndRefund: 'واپسی اور رقم واپس کریں',
    returnHistory: 'واپسی کی تاریخ',
    noReturnsYet: 'ابھی تک کوئی واپسی نہیں ہوئی',
    returnType: 'واپسی کی قسم',
    fullReturn: 'مکمل واپسی',
    returnAllItems: 'تمام اشیاء واپس کریں',
    partialReturn: 'جزوی واپسی',
    selectSpecificItems: 'مخصوص اشیاء منتخب کریں',
    itemsToReturn: 'واپس کرنے والی اشیاء',
    returnQty: 'واپسی کی مقدار',
    returnReason: 'واپسی کی وجہ *',
    selectAReason: 'وجہ منتخب کریں...',
    defectiveProduct: 'خراب مصنوعات',
    wrongItemDelivered: 'غلط آئٹم بھیجا گیا',
    customerChangedMind: 'گاہک نے ارادہ بدل دیا',
    expiredProduct: 'میعاد ختم شدہ مصنوعات',
    qualityIssues: 'معیار کے مسائل',
    other: 'دیگر',
    refundAmount: 'واپسی کی رقم',
    profitMargin: '30% منافع',
    walkIn: 'واک ان',
    reasonLabel: 'وجہ',
    
    // Forecasting
    demandForecasting: 'طلب کی پیشن گوئی اور تجزیہ',
    forecastingDescription: 'انوینٹری کی سطح کو بہتر بنانے اور اسٹاک ختم ہونے سے روکنے کے لیے پیشن گوئی',
    analysisPeriod: 'تجزیے کی مدت',
    last60Days: 'آخری 60 دن',
    last90Days: 'آخری 90 دن',
    criticalItems: 'نازک اشیاء',
    needsImmediateAttention: 'فوری توجہ درکار ہے',
    stockoutRisk: 'اسٹاک ختم ہونے کا خطرہ',
    within14Days: '14 دنوں کے اندر',
    highDemandItems: 'زیادہ طلب والی اشیاء',
    strongSalesVelocity: 'فروخت کی تیز رفتار',
    reorderRequired: 'دوبارہ آرڈر ضروری',
    belowReorderPoint: 'دوبارہ آرڈر کی حد سے نیچے',
    stockLevelForecast: 'اسٹاک کی سطح کی پیشن گوئی (اگلے 30 دن)',
    criticalStockAlerts: 'نازک اسٹاک الرٹس',
    currentStockLabel: 'موجودہ اسٹاک',
    avgDailySales: 'اوسط یومیہ فروخت',
    daysUntilStockout: 'اسٹاک ختم ہونے تک کے دن',
    reorderRecommendations: 'دوبارہ آرڈر کی سفارشات',
    reorderPointLabel: 'دوبارہ آرڈر کی حد',
    suggestedOrder: 'تجویز کردہ آرڈر',
    unitsLabel: 'یونٹس',
    reorderNow: 'ابھی آرڈر کریں',
    allItemsWellStocked: 'تمام اشیاء کا اسٹاک مناسب ہے!',
    highDemand: 'زیادہ طلب',
    mediumDemand: 'درمیانہ',
    lowDemandLabel: 'کم طلب',
    noSalesLabel: 'کوئی فروخت نہیں',
    lowDemandItems: 'کم طلب / سست چلنے والی اشیاء',
    considerPromotion: 'پروموشن یا کلیئرنس پر غور کریں',
    allItemsGoodVelocity: 'تمام اشیاء کی فروخت کی رفتار اچھی ہے',
    stockoutRiskTimeline: 'اسٹاک ختم ہونے کا خطرہ ٹائم لائن (اگلے 14 دن)',
    untilStockout: 'اسٹاک ختم ہونے تک',
    dailyRate: 'یومیہ شرح',
    unitsPerDay: 'یونٹس/دن',
    noHighDemandItems: 'اس مدت میں زیادہ طلب والی اشیاء نہیں',
    soldLabel: 'فروخت',
    dailyAvg: 'یومیہ اوسط',
    forecasting: 'پیشن گوئی',
    
    // VoiceBilling - Additional
    billingSystem: 'بلنگ سسٹم',
    transcribed: 'تحریر شدہ',
    parsedItemLabel: 'شناخت شدہ آئٹم',
    itemNameLabel: 'آئٹم کا نام',
    quantityLabel: 'مقدار',
    unitPriceLabel: 'یونٹ کی قیمت',
    totalLabel: 'کل',
    addToBill: 'بل میں شامل کریں',
    loadingItems: 'اشیاء لوڈ ہو رہی ہیں...',
    tryAddingItemsFirst: 'پہلے انوینٹری صفحے میں اشیاء شامل کریں',
    
    // Header
    welcomeUser: 'خوش آمدید',
    
    // Sidebar - Additional
    sales: 'فروخت',
    
    // Login - Additional
    brandName: 'ای-انوینٹری',
    brandTagline: 'آن لائن انوینٹری مینجمنٹ سسٹم',
    emailAddress: 'ای میل ایڈریس',
    keepMeLoggedIn: 'مجھے لاگ ان رکھیں',
    loggingIn: 'لاگ ان ہو رہا ہے...',
    logIn: 'لاگ ان',
    loginWithVoice: 'آواز سے لاگ ان',
    registerHere: 'یہاں رجسٹر کریں',
    voiceLoginTitle: 'وائس لاگ ان',
    verifying: 'تصدیق ہو رہی ہے...',
    recordingClickToStop: 'ریکارڈنگ... رکنے کے لیے کلک کریں',
    tapToSpeak: 'بولنے کے لیے ٹیپ کریں',
    backToEmailLogin: 'ای میل لاگ ان پر واپس جائیں',
    
    // Register - Additional
    createAccount: 'اکاؤنٹ بنائیں',
    creatingAccount: 'اکاؤنٹ بنایا جا رہا ہے...',
    passwordsDoNotMatch: 'پاس ورڈ مماثل نہیں ہیں',
    passwordMinLength: 'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے',
    
    // Receipt - Additional
    newBill: 'نیا بل',
    printReceipt: 'رسید پرنٹ کریں',
    
    // Bill History - Additional
    todaysBills: 'آج کے بل',
    billDetails: 'بل کی تفصیلات',
    
    // Settings - Additional voice
    recordingDuration: 'ریکارڈنگ... (5 سیکنڈ)',
    voiceRecorded: 'آواز ریکارڈ ہو گئی!',
    tapToRecord: 'ریکارڈ کرنے کے لیے ٹیپ کریں',
    readParagraphWhileRecording: 'ریکارڈنگ کے دوران اوپر کا پیراگراف پڑھیں',
    registerThisVoice: 'یہ آواز رجسٹر کریں',
    reRecord: 'دوبارہ ریکارڈ',

    // Header and global search - Additional
    unnamedItem: 'بغیر نام آئٹم',
    featureLabel: 'فیچر',
    userFallback: 'صارف',
    searching: 'تلاش جاری ہے...',
    switchToLightMode: 'روشن موڈ پر جائیں',
    switchToDarkMode: 'تاریک موڈ پر جائیں',
    stockAlerts: 'اسٹاک الرٹس',
    alertSingle: 'الرٹ',
    alertsPlural: 'الرٹس',
    criticalStockOnlyLeft: 'نازک اسٹاک - صرف باقی',
    lowStockLeft: 'کم اسٹاک - باقی',
    reorderAt: 'دوبارہ آرڈر کی حد',
    confirmLogoutTitle: 'لاگ آؤٹ کی تصدیق',
    confirmLogoutGuestModeMessage: 'کیا آپ واقعی لاگ آؤٹ کرنا چاہتے ہیں؟ آپ کو گیسٹ موڈ میں منتقل کر دیا جائے گا۔',
    yesLogout: 'ہاں، لاگ آؤٹ',

    // Settings account edit - Additional
    editAccountInfo: 'اکاؤنٹ معلومات میں ترمیم',
    pleaseLoginToEditAccount: 'اکاؤنٹ کی معلومات میں ترمیم کے لیے پہلے لاگ ان کریں۔',
    newPassword: 'نیا پاس ورڈ',
    leaveEmptyToKeepCurrent: 'موجودہ پاس ورڈ برقرار رکھنے کے لیے خالی چھوڑ دیں',
    reEnterNewPassword: 'نیا پاس ورڈ دوبارہ درج کریں',
    saving: 'محفوظ کیا جا رہا ہے...',
    saveChanges: 'تبدیلیاں محفوظ کریں',
    usernameRequired: 'صارف نام لازمی ہے',
    emailRequired: 'ای میل لازمی ہے',
    profileUpdatedSuccessfully: 'پروفائل کامیابی سے اپ ڈیٹ ہو گئی',
    failedToUpdateProfile: 'پروفائل اپ ڈیٹ کرنے میں ناکامی',
    pleaseRecordVoiceFirst: 'براہ کرم پہلے اپنی آواز ریکارڈ کریں',
    voiceRegisteredSuccessMessage: 'آواز کامیابی سے رجسٹر ہو گئی! اب آپ آواز سے لاگ ان کر سکتے ہیں۔',
    voiceRegistrationFailed: 'آواز رجسٹر کرنے میں ناکامی',
    voiceRegistrationParagraph: 'براہ کرم یہ عبارت پڑھیں: "تیز بھورا لومڑی سست کتے کے اوپر کودتی ہے۔ میری آواز ہی میرا پاس ورڈ ہے۔"',
    
    // Reports - Additional
    loadingReports: 'رپورٹس لوڈ ہو رہی ہیں...',
    salesCount: 'فروخت کی تعداد',
    perSale: 'فی فروخت',
    profitMarginPct: '20% منافع',
    
    // Inventory - Additional
    retryConnection: 'دوبارہ کوشش کریں',
    loadingItemsMsg: 'اشیاء لوڈ ہو رہی ہیں...',
    
    // Sales table headers
    searchByBillOrCustomer: 'بل نمبر یا گاہک کے نام سے تلاش کریں...',
    qtyLabel: 'مقدار',
    priceLabel: 'قیمت',
    billLabel: 'بل',
    daysLabel: 'دن',
    currentLabel: 'موجودہ',
    predictedDemand30d: 'متوقع طلب (30 دن)',
    
    // Misc
    egAhmedAli: 'مثال، احمد علی',
    loadingData: 'ڈیٹا لوڈ ہو رہا ہے...',
    failedToLoadData: 'ڈیٹا لوڈ کرنے میں ناکامی۔ براہ کرم دوبارہ کوشش کریں۔',
    unableToLoadPlsRefresh: 'ڈیٹا لوڈ نہیں ہو سکا۔ براہ کرم صفحہ ریفریش کریں۔',
    deleteLabel: 'حذف کریں',

    // Alert dialog
    ok: 'ٹھیک ہے',
    alertError: 'خرابی',
    alertSuccess: 'کامیاب',
    alertWarning: 'انتباہ',
    alertInfo: 'معلومات',

    // VoiceBilling alerts
    failedToLoadItems: 'اشیاء لوڈ کرنے میں ناکامی',
    pleaseTryAgain: 'براہ کرم دوبارہ کوشش کریں',
    insufficientStock: 'ناکافی اسٹاک',
    insufficientStockMsg: 'دستیاب: {stock} {unit}',
    noItemsInBill: 'بل میں کوئی آئٹم نہیں!',
    itemNotFoundInInventory: '{name} انونٹری میں نہیں ملا!',
    insufficientStockForItem: '{name} کے لیے ناکافی اسٹاک! دستیاب: {stock} {unit}',
    failedToAddToUdhar: 'ادھار میں شامل کرنے میں ناکامی',
    failedToUpdateInventory: 'انونٹری اپ ڈیٹ کرنے میں ناکامی',
    pleaseEnterValidQty: 'براہ کرم درست مقدار درج کریں',
    onlyXAvailable: 'صرف {stock} {unit} دستیاب ہے!',

    // Inventory alerts
    failedToAddItem: 'آئٹم شامل کرنے میں ناکامی',
    failedToUpdateItem: 'آئٹم اپ ڈیٹ کرنے میں ناکامی',
    confirmDeleteItem: 'کیا آپ واقعی یہ آئٹم حذف کرنا چاہتے ہیں؟',

    // UdharKhata alerts
    pleaseEnterCustomerName: 'براہ کرم گاہک کا نام درج کریں',
    failedToAddEntry: 'اندراج شامل کرنے میں ناکامی',
    pleaseEnterValidAmountGt0: 'براہ کرم 0 سے زیادہ رقم درج کریں',
    failedToAddUdhar: 'ادھار شامل کرنے میں ناکامی',
    confirmDeleteCustomer: 'کیا آپ واقعی {name} کو حذف کرنا چاہتے ہیں؟ اس سے ان کے تمام ریکارڈ حذف ہو جائیں گے۔',
    customerDeletedSuccess: 'گاہک کامیابی سے حذف ہو گیا!',
    failedToDeleteCustomer: 'حذف کرنے میں ناکامی',
    pleaseEnterValidAmount: 'براہ کرم درست رقم درج کریں',
    paymentExceedsUdhar: 'ادائیگی کی رقم موجودہ ادھار رقم سے زیادہ نہیں ہو سکتی',
    failedToProcessPayment: 'ادائیگی میں ناکامی',

    // BillHistory alerts
    failedToLoadBills: 'بل لوڈ کرنے میں ناکامی',

    // Reports alerts
    noReportData: 'ڈاؤن لوڈ کے لیے کوئی رپورٹ ڈیٹا دستیاب نہیں۔',
    failedToDownloadReport: 'رپورٹ ڈاؤن لوڈ کرنے میں ناکامی۔ براہ کرم دوبارہ کوشش کریں۔',

    // Sales alerts
    pleaseSelectItemsToReturn: 'براہ کرم واپسی کے لیے اشیاء منتخب کریں',
    pleaseProvideReturnReason: 'براہ کرم واپسی کی وجہ بتائیں',
    returnProcessedSuccess: 'واپسی کامیابی سے مکمل!',
    refundAmountLabel: 'ریفنڈ رقم: ₨{amount}',
    failedToProcessReturn: 'واپسی میں ناکامی۔ براہ کرم دوبارہ کوشش کریں۔',
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('english')

  useEffect(() => {
    // Load saved language from localStorage
    const savedLanguage = localStorage.getItem('ims_language')
    if (savedLanguage && (savedLanguage === 'english' || savedLanguage === 'urdu')) {
      setLanguage(savedLanguage)
    }
  }, [])

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage)
    localStorage.setItem('ims_language', newLanguage)
  }

  const t = (key) => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
