import React, { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

export const translations = {
  english: {
    // Common
    search: 'Search',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    close: 'Close',
    submit: 'Submit',
    refresh: 'Refresh',
    welcome: 'Welcome',
    processing: 'Processing...',
    loading: 'Loading...',
    noData: 'No data available',
    error: 'Error',
    success: 'Success',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    
    // Header
    aiVoiceBilling: 'AI Voice Billing',
    signUpFree: 'Sign Up Free',
    
    // Guest Banner
    exploringDemoMode: "You're exploring Demo Mode",
    withSampleData: 'with sample data',
    signUpToSave: '— Sign up free to save your real inventory, bills, and customer data!',
    
    // Authentication
    login: 'Sign In',
    register: 'Sign Up',
    signIn: 'Sign in',
    signUp: 'Sign up',
    username: 'User Name',
    password: 'Password',
    email: 'Email',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    chooseLoginMethod: 'Choose your preferred login method',
    createAccountMessage: 'Create an account to get started',
    loginWelcomeMessage: 'Experience the future of billing with AI-powered voice recognition and smart inventory management.',
    registerWelcomeMessage: 'Join us to unlock powerful features for your business with AI-powered voice billing and inventory management.',
    
    // Sidebar
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    voiceBilling: 'Voice Billing',
    udharKhata: 'Udhar Khata',
    billHistory: 'Bill History',
    reports: 'Reports',
    settings: 'Settings',
    logout: 'Logout',
    confirmLogout: 'Are you sure you want to logout?',
    
    // Dashboard
    todaySales: "Today's Sales",
    totalItems: 'Total Items',
    lowStock: 'Low Stock',
    udharAmount: 'Udhar Amount',
    topSellingItems: 'Top Selling Items',
    lowStockAlerts: 'Low Stock Alerts',
    itemName: 'Item Name',
    stock: 'Stock',
    status: 'Status',
    action: 'Action',
    restock: 'Restock',
    quickActions: 'Quick Actions',
    inStock: 'in stock',
    
    // Inventory
    inventoryManagement: 'Inventory Management',
    addNewItem: 'Add New Item',
    price: 'Price',
    unit: 'Unit',
    quantity: 'Quantity',
    outOfStock: 'Out of Stock',
    critical: 'Critical',
    low: 'Low',
    good: 'Good',
    searchItems: 'Search items...',
    allStatus: 'All Status',
    actions: 'Actions',
    noItemsFound: 'No items found',
    
    // Voice Billing
    manualBilling: 'Manual Billing',
    voiceInputBilling: 'Voice Input Billing',
    cart: 'Cart',
    total: 'Total',
    generateBill: 'Generate Bill',
    clearCart: 'Clear Cart',
    addToCart: 'Add to Cart',
    availableItems: 'Available Items',
    currentBill: 'Current Bill',
    clickMicrophoneToSpeak: 'Click microphone to speak',
    available: 'Available',
    cash: 'Cash',
    credit: 'Credit',
    selectCustomer: 'Select Customer',
    addToUdhar: 'Add to Udhar',
    payNow: 'Pay Now',
    paymentMethod: 'Payment Method',
    cashPayment: 'Cash Payment',
    udharPayment: 'Udhar Payment',
    searchCustomer: 'Search for customer...',
    selectPaymentType: 'Select Payment Type',
    
    // Udhar Khata
    udharManagement: 'Udhar Management',
    addCustomer: 'Add Customer',
    customerName: 'Customer Name',
    totalUdhar: 'Total Udhar',
    viewDetails: 'View Details',
    totalUnpaid: 'Total Unpaid',
    totalPaid: 'Total Paid',
    totalCustomers: 'Total Customers',
    filter: 'Filter',
    all: 'All',
    unpaid: 'Unpaid',
    paid: 'Paid',
    addNewEntry: 'Add New Entry',
    pending: 'PENDING',
    completed: 'COMPLETED',
    payUdhar: 'Pay Udhar',
    completedPayments: 'Completed payments',
    addNewUdharEntry: 'Add New Udhar Entry',
    addEntry: 'Add Entry',
    addUdharAmount: 'Add Udhar Amount',
    amountToAdd: 'Amount to Add',
    enterAmountToAdd: 'Enter amount to add',
    newTotalWillBe: 'New total will be',
    cannotDeleteCustomer: 'Cannot Delete Customer',
    stillHasPending: 'still has pending udhar of',
    collectRemaining: 'Please collect the remaining udhar amount before deleting this customer.',
    close: 'Close',
    payUdharNow: 'Pay Udhar Now',
    currentAmount: 'Current Amount',
    paymentAmount: 'Payment Amount',
    enterAmountToPay: 'Enter amount to pay',
    remainingAmount: 'Remaining Amount',
    submit: 'Submit',
    noCustomersFound: 'No customers found',
    processPayment: 'Process Payment',
    maximum: 'Maximum',
    
    // Voice Billing
    manualBilling: 'Manual Billing',
    voiceInputBilling: 'Voice Input Billing',
    cart: 'Cart',
    total: 'Total',
    generateBill: 'Generate Bill',
    clearCart: 'Clear Cart',
    addToCart: 'Add to Cart',
    
    // Udhar Khata
    udharManagement: 'Udhar Management',
    addCustomer: 'Add Customer',
    customerName: 'Customer Name',
    totalUdhar: 'Total Udhar',
    viewDetails: 'View Details',
    
    // Reports
    reportsAnalytics: 'Reports & Analytics',
    dateRange: 'Date Range',
    category: 'Category',
    allCategories: 'All Categories',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    thisYear: 'This Year',
    totalRevenue: 'Total Revenue',
    totalProfit: 'Total Profit',
    totalTransactions: 'Total Transactions',
    avgTransaction: 'Avg. Transaction',
    dailySalesTrend: 'Daily Sales Trend',
    itemFrequency: 'Item Frequency',
    salesSummary: 'Sales Summary',
    product: 'Product',
    totalSale: 'Total Sale',
    generating: 'Generating...',
    downloadReport: 'Download Report',
    noDataAvailable: 'No data available',
    noSalesData: 'No sales data for the selected period',
    profit: 'Profit',
    
    // Settings
    settingsTitle: 'Settings',
    appearance: 'Appearance',
    themeMode: 'Theme Mode',
    light: 'Light',
    dark: 'Dark',
    language: 'Language',
    displayLanguage: 'Display Language',
    userManagement: 'User Management',
    about: 'About',
    version: 'Version',
    builtWith: 'Built with',
    purpose: 'Purpose',
    
    // Bill History
    billHistoryTitle: 'Bill History',
    viewAndManageBills: 'View and manage all generated bills',
    todayTotal: "Today's Total",
    cashSales: 'Cash Sales',
    udharSales: 'Udhar Sales',
    searchBillOrCustomer: 'Search bill number or customer...',
    paymentType: 'Payment Type',
    allPayments: 'All Payments',
    allBills: 'All Bills',
    cashOnly: 'Cash Only',
    creditOnly: 'Credit Only',
    startDate: 'Start Date',
    endDate: 'End Date',
    billNumber: 'Bill Number',
    customer: 'Customer',
    date: 'Date',
    dateTime: 'Date & Time',
    type: 'Type',
    amount: 'Amount',
    items: 'Items',
    walkInCustomer: 'Walk-in Customer',
    viewReceipt: 'View Receipt',
    noBillsFound: 'No bills found',
    deleteBillConfirm: 'Are you sure you want to delete this bill?',
    billDeleted: 'Bill deleted successfully!',
    failedToDeleteBill: 'Failed to delete bill',
    
    // Voice Billing - Additional
    noItemsAdded: 'No items added yet. Use voice command to add items.',
    qty: 'Qty',
    totalItems: 'Total Items',
    grandTotal: 'Grand Total',
    item: 'Item',
    completeBill: 'Complete Bill',
    totalAmount: 'Total Amount',
    howToProceed: 'How would you like to proceed?',
    creditSale: 'Credit Sale',
    viewBill: 'View Bill',
    searchForCustomer: 'Search for customer to add',
    toTheirUdhar: 'to their Udhar',
    searchCustomerName: 'Search customer name...',
    currentUdhar: 'Current Udhar',
    newTotal: 'New Total',
    noCustomerFound: 'No customer found with name',
    addCustomerFirst: 'Please add this customer in Udhar Khata first',
    success: 'Success!',
    addedToUdhar: 'added to',
    udharAccount: "'s Udhar account.",
    inventoryUpdated: 'Inventory updated!',
    transactionId: 'Transaction ID:',
    paidBy: 'Paid By:',
    purchase: 'PURCHASE',
    subTotal: 'Sub Total',
    salesTax: 'Sales Tax',
    thankYou: 'THANK YOU FOR',
    yourPurchase: 'YOUR PURCHASE',
    print: 'Print',
    visitAgain: 'Visit us again!',
    transactionCompleted: 'Transaction completed successfully',
    billGeneratedSuccess: 'Bill generated successfully! Inventory has been updated.',
    addNewItem: 'Add New Item',
    editItem: 'Edit Item',
    itemName: 'Item Name',
    egSugar: 'e.g., Sugar',
    stock: 'Stock',
    unit: 'Unit',
    unitPrice: 'Unit Price',
    addItem: 'Add Item',
    updateItem: 'Update Item',
    confirmDelete: 'Are you sure you want to delete this item?',
    failedToDelete: 'Failed to delete item',
    cannotDeleteItem: 'Cannot delete this item because it has related records',
    
    // Udhar Khata - Additional
    addUdhar: 'Add Udhar',
    
    // Settings - Additional
    voiceAuthentication: 'Voice Authentication',
    registerVoice: 'Register Voice',
    notRegistered: 'Not registered',
    registerVoiceDesc: 'Register your voice to enable voice-based login. This is an additional security feature.',
    owner: 'Owner',
    registered: 'Registered',
    checking: 'Checking...',
    reRegisterVoice: 'Re-register Voice',
    voiceRegisteredDesc: 'Your voice is registered. You can now login using voice authentication.',
    readThisParagraph: 'Read this paragraph clearly:',
    processingVoice: 'Processing your voice...',
    noUserLoggedIn: 'No user logged in',
    active: 'Active',
    
    // Reports - Additional
    totalSale: 'Total Sale',
    
    // Login/Register
    fullName: 'Full Name',
    confirmPassword: 'Confirm Password',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
  },
  urdu: {
    // Common
    search: 'تلاش کریں',
    save: 'محفوظ کریں',
    cancel: 'منسوخ کریں',
    delete: 'حذف کریں',
    edit: 'تدوین کریں',
    add: 'شامل کریں',
    close: 'بند کریں',
    submit: 'جمع کرائیں',
    refresh: 'تازہ کریں',
    welcome: 'خوش آمدید',
    processing: 'کارروائی جاری ہے...',
    loading: 'لوڈ ہو رہا ہے...',
    noData: 'کوئی ڈیٹا دستیاب نہیں',
    error: 'خرابی',
    success: 'کامیابی',
    confirm: 'تصدیق کریں',
    yes: 'ہاں',
    no: 'نہیں',
    
    // Header
    aiVoiceBilling: 'اے آئی وائس بلنگ',
    signUpFree: 'مفت سائن اپ',
    
    // Guest Banner
    exploringDemoMode: 'آپ ڈیمو موڈ دیکھ رہے ہیں',
    withSampleData: 'نمونہ ڈیٹا کے ساتھ',
    signUpToSave: '— اپنی حقیقی انوینٹری، بل اور گاہک کا ڈیٹا محفوظ کرنے کے لیے مفت سائن اپ کریں!',
    
    // Authentication
    login: 'سائن ان',
    register: 'رجسٹر کریں',
    signIn: 'سائن ان',
    signUp: 'رجسٹر کریں',
    username: 'صارف کا نام',
    password: 'پاس ورڈ',
    email: 'ای میل',
    dontHaveAccount: 'اکاؤنٹ نہیں ہے؟',
    alreadyHaveAccount: 'پہلے سے اکاؤنٹ ہے؟',
    chooseLoginMethod: 'اپنا پسندیدہ لاگ ان طریقہ منتخب کریں',
    createAccountMessage: 'شروع کرنے کے لیے ایک اکاؤنٹ بنائیں',
    loginWelcomeMessage: 'AI سے چلنے والی وائس ریکگنیشن اور سمارٹ انوینٹری مینجمنٹ کے ساتھ بلنگ کے مستقبل کا تجربہ کریں۔',
    registerWelcomeMessage: 'AI سے چلنے والی وائس بلنگ اور انوینٹری مینجمنٹ کے ساتھ اپنے کاروبار کے لیے طاقتور خصوصیات کو غیر مقفل کرنے کے لیے ہم سے جڑیں۔',
    
    // Sidebar
    dashboard: 'ڈیش بورڈ',
    inventory: 'انوینٹری',
    voiceBilling: 'وائس بلنگ',
    udharKhata: 'ادھار کھاتہ',
    billHistory: 'بل کی تاریخ',
    reports: 'رپورٹس',
    settings: 'ترتیبات',
    logout: 'لاگ آؤٹ',
    confirmLogout: 'کیا آپ واقعی لاگ آؤٹ کرنا چاہتے ہیں؟',
    
    // Dashboard
    todaySales: 'آج کی فروخت',
    totalItems: 'کل اشیاء',
    lowStock: 'کم اسٹاک',
    udharAmount: 'ادھار رقم',
    topSellingItems: 'زیادہ فروخت ہونے والی اشیاء',
    lowStockAlerts: 'کم اسٹاک الرٹس',
    itemName: 'آئٹم کا نام',
    stock: 'اسٹاک',
    status: 'حالت',
    action: 'ایکشن',
    restock: 'دوبارہ اسٹاک',
    quickActions: 'فوری کارروائیاں',
    inStock: 'اسٹاک میں',
    todayTotal: 'آج کا کل',
    
    // Inventory
    inventoryManagement: 'انوینٹری مینجمنٹ',
    addNewItem: 'نیا آئٹم شامل کریں',
    price: 'قیمت',
    unit: 'یونٹ',
    quantity: 'مقدار',
    outOfStock: 'اسٹاک ختم',
    critical: 'نازک',
    low: 'کم',
    good: 'اچھا',
    searchItems: 'اشیاء تلاش کریں...',
    allStatus: 'تمام حالت',
    actions: 'اقدامات',
    noItemsFound: 'کوئی آئٹم نہیں ملا',
    
    // Voice Billing
    manualBilling: 'دستی بلنگ',
    voiceInputBilling: 'آواز سے بلنگ',
    cart: 'کارٹ',
    total: 'کل',
    generateBill: 'بل بنائیں',
    clearCart: 'کارٹ صاف کریں',
    addToCart: 'کارٹ میں شامل کریں',
    availableItems: 'دستیاب اشیاء',
    currentBill: 'موجودہ بل',
    clickMicrophoneToSpeak: 'بولنے کے لیے مائیکروفون پر کلک کریں',
    available: 'دستیاب',
    cash: 'نقد',
    credit: 'ادھار',
    selectCustomer: 'گاہک منتخب کریں',
    addToUdhar: 'ادھار میں شامل کریں',
    payNow: 'ابھی ادا کریں',
    paymentMethod: 'ادائیگی کا طریقہ',
    cashPayment: 'نقد ادائیگی',
    udharPayment: 'ادھار ادائیگی',
    searchCustomer: 'گاہک تلاش کریں...',
    selectPaymentType: 'ادائیگی کی قسم منتخب کریں',
    
    // Udhar Khata
    udharManagement: 'ادھار مینجمنٹ',
    addCustomer: 'نیا گاہک شامل کریں',
    customerName: 'گاہک کا نام',
    totalUdhar: 'کل ادھار',
    viewDetails: 'تفصیلات دیکھیں',
    totalUnpaid: 'کل ادائیگی نہیں',
    totalPaid: 'کل ادا شدہ',
    totalCustomers: 'کل گاہک',
    filter: 'فلٹر',
    all: 'تمام',
    unpaid: 'ادائیگی نہیں',
    paid: 'ادا شدہ',
    addNewEntry: 'نیا اندراج شامل کریں',
    pending: 'زیر التواء',
    completed: 'مکمل',
    payUdhar: 'ادھار ادا کریں',
    completedPayments: 'مکمل ادائیگیاں',
    addNewUdharEntry: 'نیا ادھار اندراج شامل کریں',
    addEntry: 'اندراج شامل کریں',
    addUdharAmount: 'ادھار رقم شامل کریں',
    amountToAdd: 'شامل کرنے کی رقم',
    enterAmountToAdd: 'شامل کرنے کی رقم درج کریں',
    newTotalWillBe: 'نیا کل ہوگا',
    cannotDeleteCustomer: 'گاہک حذف نہیں کر سکتے',
    stillHasPending: 'ابھی بھی باقی ہے ادھار',
    collectRemaining: 'براہ کرم اس گاہک کو حذف کرنے سے پہلے باقی ادھار رقم وصول کریں۔',
    close: 'بند کریں',
    payUdharNow: 'ابھی ادھار ادا کریں',
    currentAmount: 'موجودہ رقم',
    paymentAmount: 'ادائیگی کی رقم',
    enterAmountToPay: 'ادا کرنے کی رقم درج کریں',
    remainingAmount: 'باقی رقم',
    submit: 'جمع کرائیں',
    noCustomersFound: 'کوئی گاہک نہیں ملا',
    processPayment: 'ادائیگی کی کارروائی',
    maximum: 'زیادہ سے زیادہ',
    
    // Voice Billing
    manualBilling: 'دستی بلنگ',
    voiceInputBilling: 'آواز سے بلنگ',
    cart: 'کارٹ',
    total: 'کل',
    generateBill: 'بل بنائیں',
    clearCart: 'کارٹ صاف کریں',
    addToCart: 'کارٹ میں شامل کریں',
    
    // Udhar Khata
    udharManagement: 'ادھار مینجمنٹ',
    addCustomer: 'نیا گاہک شامل کریں',
    customerName: 'گاہک کا نام',
    totalUdhar: 'کل ادھار',
    viewDetails: 'تفصیلات دیکھیں',
    
    // Reports
    reportsAnalytics: 'رپورٹس اور تجزیہ',
    dateRange: 'تاریخ کی حد',
    category: 'زمرہ',
    allCategories: 'تمام زمرے',
    today: 'آج',
    thisWeek: 'اس ہفتے',
    thisMonth: 'اس ماہ',
    thisYear: 'اس سال',
    totalRevenue: 'کل آمدنی',
    totalProfit: 'کل منافع',
    totalTransactions: 'کل لین دین',
    avgTransaction: 'اوسط لین دین',
    dailySalesTrend: 'روزانہ فروخت کا رجحان',
    itemFrequency: 'آئٹم کی تعدد',
    salesSummary: 'فروخت کا خلاصہ',
    product: 'پروڈکٹ',
    totalSale: 'کل فروخت',
    generating: 'تیار کیا جا رہا ہے...',
    downloadReport: 'رپورٹ ڈاؤن لوڈ کریں',
    noDataAvailable: 'کوئی ڈیٹا دستیاب نہیں',
    noSalesData: 'منتخب مدت کے لیے کوئی فروخت کا ڈیٹا نہیں',
    profit: 'منافع',
    
    // Settings
    settingsTitle: 'ترتیبات',
    appearance: 'ظاہری شکل',
    themeMode: 'تھیم موڈ',
    light: 'روشن',
    dark: 'تاریک',
    language: 'زبان',
    displayLanguage: 'ڈسپلے زبان',
    userManagement: 'صارف کا انتظام',
    about: 'کے بارے میں',
    version: 'ورژن',
    builtWith: 'بنایا گیا',
    purpose: 'مقصد',
    
    // Bill History
    billHistoryTitle: 'بل کی تاریخ',
    viewAndManageBills: 'تمام بنائے گئے بل دیکھیں اور ان کا انتظام کریں',
    cashSales: 'نقد فروخت',
    udharSales: 'ادھار فروخت',
    searchBillOrCustomer: 'بل نمبر یا گاہک تلاش کریں...',
    paymentType: 'ادائیگی کی قسم',
    allPayments: 'تمام ادائیگیاں',
    allBills: 'تمام بل',
    cashOnly: 'صرف نقد',
    creditOnly: 'صرف ادھار',
    startDate: 'شروع کی تاریخ',
    endDate: 'اختتام کی تاریخ',
    billNumber: 'بل نمبر',
    customer: 'گاہک',
    date: 'تاریخ',
    dateTime: 'تاریخ اور وقت',
    type: 'قسم',
    amount: 'رقم',
    items: 'اشیاء',
    walkInCustomer: 'واک ان گاہک',
    viewReceipt: 'رسید دیکھیں',
    noBillsFound: 'کوئی بل نہیں ملا',
    deleteBillConfirm: 'کیا آپ واقعی یہ بل حذف کرنا چاہتے ہیں؟',
    billDeleted: 'بل کامیابی سے حذف ہو گیا!',
    failedToDeleteBill: 'بل حذف کرنے میں ناکامی',
    
    // Voice Billing - Additional
    noItemsAdded: 'ابھی تک کوئی آئٹم شامل نہیں کیا گیا۔ آئٹم شامل کرنے کے لیے وائس کمانڈ استعمال کریں۔',
    qty: 'مقدار',
    totalItems: 'کل اشیاء',
    grandTotal: 'مجموعی کل',
    item: 'آئٹم',
    completeBill: 'بل مکمل کریں',
    totalAmount: 'کل رقم',
    howToProceed: 'آپ کیسے آگے بڑھنا چاہتے ہیں؟',
    creditSale: 'ادھار فروخت',
    viewBill: 'بل دیکھیں',
    searchForCustomer: 'گاہک تلاش کریں',
    toTheirUdhar: 'ان کے ادھار میں شامل کریں',
    searchCustomerName: 'گاہک کا نام تلاش کریں...',
    currentUdhar: 'موجودہ ادھار',
    newTotal: 'نیا کل',
    noCustomerFound: 'کوئی گاہک نہیں ملا',
    addCustomerFirst: 'براہ کرم پہلے اس گاہک کو ادھار کھاتہ میں شامل کریں',
    success: 'کامیابی!',
    addedToUdhar: 'میں شامل',
    udharAccount: 'کے ادھار اکاؤنٹ میں۔',
    inventoryUpdated: 'انوینٹری اپ ڈیٹ ہو گئی!',
    transactionId: 'لین دین کی شناخت:',
    paidBy: 'ادا کنندہ:',
    purchase: 'خریداری',
    subTotal: 'ذیلی کل',
    salesTax: 'سیلز ٹیکس',
    thankYou: 'آپ کا شکریہ',
    yourPurchase: 'آپ کی خریداری کے لیے',
    print: 'پرنٹ',
    visitAgain: 'دوبارہ تشریف لائیں!',
    transactionCompleted: 'لین دین کامیابی سے مکمل ہو گیا',
    billGeneratedSuccess: 'بل کامیابی سے بن گیا! انوینٹری اپ ڈیٹ ہو گئی۔',
    addNewItem: 'نیا آئٹم شامل کریں',
    editItem: 'آئٹم میں ترمیم کریں',
    itemName: 'آئٹم کا نام',
    egSugar: 'مثال، چینی',
    stock: 'اسٹاک',
    unit: 'یونٹ',
    unitPrice: 'یونٹ کی قیمت',
    addItem: 'آئٹم شامل کریں',
    updateItem: 'آئٹم اپ ڈیٹ کریں',
    confirmDelete: 'کیا آپ واقعی اس آئٹم کو حذف کرنا چاہتے ہیں؟',
    failedToDelete: 'آئٹم حذف کرنے میں ناکامی',
    cannotDeleteItem: 'اس آئٹم کو حذف نہیں کیا جا سکتا کیونکہ اس کے متعلقہ ریکارڈ موجود ہیں',
    
    // Udhar Khata - Additional
    addUdhar: 'ادھار شامل کریں',
    
    // Settings - Additional
    voiceAuthentication: 'وائس کی تصدیق',
    registerVoice: 'آواز رجسٹر کریں',
    notRegistered: 'رجسٹرڈ نہیں',
    registerVoiceDesc: 'وائس پر مبنی لاگ ان کو فعال کرنے کے لیے اپنی آواز رجسٹر کریں۔ یہ ایک اضافی سیکیورٹی فیچر ہے۔',
    owner: 'مالک',
    registered: 'رجسٹرڈ',
    checking: 'چیک کر رہے ہیں...',
    reRegisterVoice: 'آواز دوبارہ رجسٹر کریں',
    voiceRegisteredDesc: 'آپ کی آواز رجسٹرڈ ہے۔ اب آپ وائس کی تصدیق کا استعمال کرتے ہوئے لاگ ان کر سکتے ہیں۔',
    readThisParagraph: 'اس پیراگراف کو واضح طور پر پڑھیں:',
    processingVoice: 'آپ کی آواز پر کارروائی ہو رہی ہے...',
    noUserLoggedIn: 'کوئی صارف لاگ ان نہیں',
    active: 'فعال',
    
    // Reports - Additional
    totalSale: 'کل فروخت',
    
    // Login/Register
    fullName: 'پورا نام',
    confirmPassword: 'پاس ورڈ کی تصدیق کریں',
    dontHaveAccount: 'اکاؤنٹ نہیں ہے؟',
    alreadyHaveAccount: 'پہلے سے اکاؤنٹ ہے؟',
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('english')

  useEffect(() => {
    // Load saved language from localStorage
    const savedLanguage = localStorage.getItem('ims_language')
    if (savedLanguage && (savedLanguage === 'english' || savedLanguage === 'urdu')) {
      setLanguage(savedLanguage)
    }
  }, [])

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage)
    localStorage.setItem('ims_language', newLanguage)
  }

  const t = (key) => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
